### ISSUE TITLE
WebSocket error with heroku

### ISSUE THREAD

**Issue by stevedekorte** [stevedekorte/p-e-e-r.net#5]
SyncAction.js:15 SyncAction169.trySend(App153.setup() order:0)  DOMException: Failed to construct 'WebSocket': The URL 'wss://peer-net-server.herokuapp.com:443443443/peerjs?key=peerjs&id=0398cac182ebe8c09b71ec4a9af7c2cb9b4ae9e07e56d34419cfa676adf4d2cfeb-0AwGl7SEYCYA5ISYly2o_05UBsn9YFGEnFmkXlWwKXoAsVdTLhMr0Hz3XINvPQQOFDRI8WMkSUjKXI5QQORrWnz1a6Yo3NtmnfsMa96ZUfM8AzOwO2L9u44e9VTt8_1eeP91968RZPyD_1YO9fEIjQwmtoPEixGxRE_0KjUlKwgA_2&token=bbqbn0n8n27' is invalid.
    at Socket._startWebSocket (file:///Users/steve/Desktop/peer/external_libs/peerjs/peer.js:1267:18)
    at Socket.start (file:///Users/steve/Desktop/peer/external_libs/peerjs/peer.js:1255:8)
    at Peer._initialize (file:///Users/steve/Desktop/peer/external_libs/peerjs/peer.js:890:15)
    at new Peer (file:///Users/steve/Desktop/peer/external_libs/peerjs/peer.js:817:10)
    at Object.connect (file:///Users/steve/Desktop/peer/src/network/webrtc/BMServerConnection.js:97:32)
    at Object.connect (file:///Users/steve/Desktop/peer/src/network/webrtc/BMRServer.js:70:33)
    at Object.connect (file:///Users/steve/Desktop/peer/src/network/webrtc/BMRServers.js:82:20)
    at Object.setupSubnodes (file:///Users/steve/Desktop/peer/src/App.js:67:34)
    at Object.setup (file:///Users/steve/Desktop/peer/src/App.js:23:14)
    at Object.send (file:///Users/steve/Desktop/peer/src/lib/notification/SyncAction.js:23:33)

**Comment by stevedekorte** [comment]
This was a problem on my side.

**Comment by richcollins** [comment]
Looks like your port is wrong: wss://peer-net-server.herokuapp.com:443443443
